use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Vendored headers ship under clickhouse-c/ inside this crate.
    // Override with CHC_INCLUDE_DIR for an out-of-tree submodule swap.
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let chc_dir = env::var("CHC_INCLUDE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest.join("clickhouse-c"));

    if !chc_dir.join("clickhouse.h").exists() {
        panic!(
            "clickhouse.h not found under {}. Set CHC_INCLUDE_DIR to your clickhouse-c checkout.",
            chc_dir.display()
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    generate_constants(&chc_dir, &out_dir);

    let mut build = cc::Build::new();
    build
        .file("src/wrapper.c")
        .include(&chc_dir)
        .std("c11")
        .warnings(true)
        .extra_warnings(true)
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-function");

    if cfg!(feature = "lz4") {
        build.define("CHC_RS_LZ4", None);
    }
    if cfg!(feature = "zstd") {
        build.define("CHC_RS_ZSTD", None);
    }

    build.compile("clickhouse_c");

    if cfg!(feature = "lz4") {
        println!("cargo:rustc-link-lib=lz4");
    }
    if cfg!(feature = "zstd") {
        println!("cargo:rustc-link-lib=zstd");
    }

    println!("cargo:rerun-if-changed=src/wrapper.c");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=CHC_INCLUDE_DIR");
    for h in [
        "clickhouse.h",
        "clickhouse-posix-io.h",
        "clickhouse-compression.h",
        "clickhouse-client.h",
        "clickhouse-lz4.h",
        "clickhouse-zstd.h",
    ] {
        let p = chc_dir.join(h);
        if p.exists() {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
    println!("cargo:include={}", chc_dir.display());
}

/* ------------------------------------------------------------------ */
/* Generator: extract enum variants + a few #defines from headers.    */
/* ------------------------------------------------------------------ */

fn generate_constants(chc_dir: &Path, out_dir: &Path) {
    let core_src = read(chc_dir, "clickhouse.h");
    let comp_src = read(chc_dir, "clickhouse-compression.h");
    let client_src = read(chc_dir, "clickhouse-client.h");

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs. Do not edit by hand.\n");
    out.push_str("// Values are scanned from the vendored clickhouse-c headers.\n\n");

    // Anonymous enum (error codes) in clickhouse.h.
    let core_enums = extract_enums(&core_src);
    let errors = core_enums
        .iter()
        .find(|(name, _)| name.is_none())
        .expect("anonymous enum (error codes) not found in clickhouse.h");
    out.push_str("// clickhouse.h: error codes (anonymous enum)\n");
    emit_enum(&mut out, &errors.1, "core::ffi::c_int");

    // Named enums.
    emit_named(
        &mut out,
        &core_enums,
        "chc_kind",
        "chc_kind",
        "clickhouse.h",
    );
    emit_named(
        &mut out,
        &core_enums,
        "chc_col_kind",
        "chc_col_kind",
        "clickhouse.h",
    );

    let comp_enums = extract_enums(&comp_src);
    emit_named(
        &mut out,
        &comp_enums,
        "chc_compression",
        "chc_compression",
        "clickhouse-compression.h",
    );

    let client_enums = extract_enums(&client_src);
    emit_named(
        &mut out,
        &client_enums,
        "chc_packet_kind",
        "chc_packet_kind",
        "clickhouse-client.h",
    );

    // #define values whose width matters in Rust.
    let msg_len = extract_define(&core_src, "CHC_ERR_MSG_LEN")
        .expect("#define CHC_ERR_MSG_LEN missing from clickhouse.h");
    out.push_str(&format!(
        "\n// clickhouse.h: #define CHC_ERR_MSG_LEN\npub const CHC_ERR_MSG_LEN: usize = {msg_len};\n"
    ));

    let revision = extract_define(&client_src, "CHC_CLIENT_DEFAULT_REVISION")
        .expect("#define CHC_CLIENT_DEFAULT_REVISION missing from clickhouse-client.h");
    out.push_str(&format!(
        "\n// clickhouse-client.h: #define CHC_CLIENT_DEFAULT_REVISION\n\
         pub const CHC_CLIENT_DEFAULT_REVISION: u64 = {revision};\n"
    ));

    fs::write(out_dir.join("sys_constants.rs"), out).expect("write sys_constants.rs");
}

fn read(dir: &Path, name: &str) -> String {
    let path = dir.join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

// (Some(tag) | None for anonymous, variants as (name, value)).
type EnumBlock = (Option<String>, Vec<(String, i64)>);

fn emit_named(
    out: &mut String,
    enums: &[EnumBlock],
    enum_name: &str,
    rust_type: &str,
    source_header: &str,
) {
    let block = enums
        .iter()
        .find(|(n, _)| n.as_deref() == Some(enum_name))
        .unwrap_or_else(|| panic!("enum {enum_name} not found in {source_header}"));
    out.push_str(&format!("\n// {source_header}: enum {enum_name}\n"));
    emit_enum(out, &block.1, rust_type);
}

fn emit_enum(out: &mut String, variants: &[(String, i64)], rust_type: &str) {
    for (name, value) in variants {
        // Drop sentinels (e.g. CHC_KIND_COUNT) — not real wire values.
        if name.ends_with("_COUNT") || name.ends_with("_LAST") {
            continue;
        }
        out.push_str(&format!("pub const {name}: {rust_type} = {value};\n"));
    }
}

/* ----- C-header scanners ------------------------------------------ */

fn strip_comments(src: &str) -> String {
    let bytes = src.as_bytes();
    let mut out = String::with_capacity(src.len());
    let mut i = 0;
    while i < bytes.len() {
        if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'/' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
        } else if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'*' {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                i += 1;
            }
            if i + 1 < bytes.len() {
                i += 2;
            }
        } else {
            out.push(bytes[i] as char);
            i += 1;
        }
    }
    out
}

fn is_ident_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

/// Returns `[(Some(name) | None, variants)]`. Variant value handles
/// explicit `= INT_LITERAL` (decimal or hex, optional u/U/l/L suffix)
/// and auto-increment from the previous variant.
fn extract_enums(src: &str) -> Vec<EnumBlock> {
    let src = strip_comments(src);
    let bytes = src.as_bytes();
    let mut results = vec![];
    let mut i = 0;
    while i + 4 <= bytes.len() {
        if &bytes[i..i + 4] == b"enum"
            && i.checked_sub(1)
                .map(|p| !is_ident_byte(bytes[p]))
                .unwrap_or(true)
            && bytes.get(i + 4).is_none_or(|b| !is_ident_byte(*b))
        {
            // Past the keyword.
            let mut j = i + 4;
            while j < bytes.len() && bytes[j].is_ascii_whitespace() {
                j += 1;
            }
            // Optional identifier (enum tag).
            let mut name: Option<String> = None;
            if j < bytes.len() && (bytes[j].is_ascii_alphabetic() || bytes[j] == b'_') {
                let start = j;
                while j < bytes.len() && is_ident_byte(bytes[j]) {
                    j += 1;
                }
                name = Some(src[start..j].to_string());
                while j < bytes.len() && bytes[j].is_ascii_whitespace() {
                    j += 1;
                }
            }
            if j < bytes.len() && bytes[j] == b'{' {
                let body_start = j + 1;
                // No nested braces inside C enums in these headers, but
                // be defensive anyway.
                let mut depth = 1;
                let mut k = body_start;
                while k < bytes.len() && depth > 0 {
                    match bytes[k] {
                        b'{' => depth += 1,
                        b'}' => depth -= 1,
                        _ => {}
                    }
                    k += 1;
                }
                if depth == 0 {
                    let body = &src[body_start..k - 1];
                    let variants = parse_enum_body(body);
                    if !variants.is_empty() {
                        results.push((name, variants));
                    }
                    i = k;
                    continue;
                }
            }
        }
        i += 1;
    }
    results
}

fn parse_enum_body(body: &str) -> Vec<(String, i64)> {
    let mut out = vec![];
    let mut next_value: i64 = 0;
    for raw in body.split(',') {
        let raw = raw.trim();
        if raw.is_empty() {
            continue;
        }
        if let Some(eq) = raw.find('=') {
            let name = raw[..eq].trim();
            let value_str = raw[eq + 1..].trim();
            let Some(value) = parse_c_integer(value_str) else {
                continue;
            };
            out.push((name.to_string(), value));
            next_value = value + 1;
        } else {
            out.push((raw.to_string(), next_value));
            next_value += 1;
        }
    }
    out
}

fn parse_c_integer(s: &str) -> Option<i64> {
    let s = s.trim();
    let s = s.trim_end_matches(['u', 'U', 'l', 'L']);
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        i64::from_str_radix(hex, 16).ok()
    } else {
        s.parse().ok()
    }
}

fn extract_define(src: &str, name: &str) -> Option<i64> {
    let src = strip_comments(src);
    for line in src.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("#define") else {
            continue;
        };
        let rest = rest.trim_start();
        let end = rest
            .find(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .unwrap_or(rest.len());
        if &rest[..end] != name {
            continue;
        }
        return parse_c_integer(rest[end..].trim_start());
    }
    None
}
